graphql:
    container_name: history
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:1234@db:5432/your_database # To be moved to environment file
    expose:
      - 5000
    ports:
      - 5000:5000
    command: ["postgraphile", "--connection", $DATABASE_URL, "--host", "0.0.0.0", "--port", "5000", "--schema", "your_schema"]
#     links:
#       - db
#     networks:
#       - psql-pgql
# networks:
#   psql-pgql: